-- Auto-generated from src/data/catalog.json by scripts/gen-seed.mjs
PRAGMA foreign_keys = ON;

INSERT INTO categories (slug, name, parent_slug, description, sort_order) VALUES ('wall-art', 'Wall Art & Prints', NULL, 'Signed watercolour reproductions, framed or as fine-art prints.', 1) ON CONFLICT(slug) DO UPDATE SET name=excluded.name, description=excluded.description, sort_order=excluded.sort_order;
INSERT INTO categories (slug, name, parent_slug, description, sort_order) VALUES ('bangalore-70s', 'Bangalore in the 70s', 'wall-art', 'The bars, bungalows, theatres and tree-lined avenues of old Bangalore.', 2) ON CONFLICT(slug) DO UPDATE SET name=excluded.name, description=excluded.description, sort_order=excluded.sort_order;
INSERT INTO categories (slug, name, parent_slug, description, sort_order) VALUES ('vintage-mumbai', 'Vintage Mumbai', 'wall-art', 'Bombay as it was — bazaars, cafes and sea-facing verandahs.', 3) ON CONFLICT(slug) DO UPDATE SET name=excluded.name, description=excluded.description, sort_order=excluded.sort_order;
INSERT INTO categories (slug, name, parent_slug, description, sort_order) VALUES ('goa', 'Goa', 'wall-art', 'Sun-washed churches, tavernas and Susegad afternoons.', 4) ON CONFLICT(slug) DO UPDATE SET name=excluded.name, description=excluded.description, sort_order=excluded.sort_order;
INSERT INTO categories (slug, name, parent_slug, description, sort_order) VALUES ('merchandise', 'Merchandise', NULL, 'The illustrations on things you can use every day.', 5) ON CONFLICT(slug) DO UPDATE SET name=excluded.name, description=excluded.description, sort_order=excluded.sort_order;
INSERT INTO categories (slug, name, parent_slug, description, sort_order) VALUES ('mugs', 'Mugs', 'merchandise', NULL, 6) ON CONFLICT(slug) DO UPDATE SET name=excluded.name, description=excluded.description, sort_order=excluded.sort_order;
INSERT INTO categories (slug, name, parent_slug, description, sort_order) VALUES ('tiles-coasters', 'Tiles & Coasters', 'merchandise', NULL, 7) ON CONFLICT(slug) DO UPDATE SET name=excluded.name, description=excluded.description, sort_order=excluded.sort_order;
INSERT INTO categories (slug, name, parent_slug, description, sort_order) VALUES ('bags', 'Bags', 'merchandise', NULL, 8) ON CONFLICT(slug) DO UPDATE SET name=excluded.name, description=excluded.description, sort_order=excluded.sort_order;
INSERT INTO categories (slug, name, parent_slug, description, sort_order) VALUES ('stationery', 'Cards & Stationery', 'merchandise', NULL, 9) ON CONFLICT(slug) DO UPDATE SET name=excluded.name, description=excluded.description, sort_order=excluded.sort_order;

INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('bangalore-club', 'Bangalore Club', 'Bangalore in the 70s', '<p>A watercolour reproduction of Paul Fernandes'' illustration of the Bangalore Club — all cane chairs, colonnades and the unhurried afternoons of a bygone city.</p><p>Every print is personally signed by the artist before it ships.</p>', 'The gracious verandahs of the Bangalore Club, rendered in watercolour and personally signed by the artist.', 650000, NULL, 'bangalore-70s', 'Bangalore in the 70s', 1, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('bangalore-palace', 'Bangalore Palace', 'Bangalore in the 70s', '<p>The Tudor-Gothic silhouette of Bangalore Palace, drawn from memory and mood. A signed reproduction from the aPaulogy gallery.</p>', 'Tudor turrets and fortified towers — the Bangalore Palace in soft watercolour.', 720000, NULL, 'bangalore-70s', 'Bangalore in the 70s', 1, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('only-place', 'The Only Place', 'Bangalore in the 70s', '<p>The Only Place — that timber-and-brick institution off Museum Road, where the steaks and the conversation were both slow-cooked. A signed watercolour print.</p>', 'The steakhouse every old Bangalorean remembers — a nostalgic corner on Museum Road.', 480000, 420000, 'bangalore-70s', 'Bangalore in the 70s', 1, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('frazer-town-underbridge', 'Frazer Town Underbridge', 'Bangalore in the 70s', '<p>A line of ducks crossing beneath the Frazer Town underbridge. One of the most-loved illustrations in the aPaulogy collection, available as a signed print.</p>', 'Ducks waddling under the Frazer Town underbridge — a small, perfect city moment.', 560000, NULL, 'bangalore-70s', 'Bangalore in the 70s', 0, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('chor-bazaar', 'Chor Bazaar', 'Vintage Mumbai', '<p>Chor Bazaar — Bombay''s legendary flea market, a jumble of brass, teak and forgotten treasure, captured in Paul Fernandes'' unmistakable watercolour hand.</p>', 'The thieves'' market of old Bombay, crammed with clocks, gramophones and stories.', 640000, NULL, 'vintage-mumbai', 'Vintage Mumbai', 1, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('cafe-mondegar', 'Cafe Mondegar', 'Vintage Mumbai', '<p>A warm watercolour of Cafe Mondegar in Colaba — cold beer, a jukebox and the murmur of the city. Signed by the artist.</p>', 'Colaba''s beloved cafe, its walls alive with Mario Miranda''s crowd.', 590000, NULL, 'vintage-mumbai', 'Vintage Mumbai', 0, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('goan-taverna', 'Goan Taverna', 'Goa', '<p>Susegad in a single frame — a Goan taverna with its blue shutters and unhurried afternoons. A signed watercolour reproduction.</p>', 'A whitewashed taverna, feni on the counter, the afternoon in no hurry.', 520000, NULL, 'goa', 'Goa', 1, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('indian-coffee-house-mug', 'Indian Coffee House Mug', 'The turbaned waiter', '<p>The turbaned waiter of the Indian Coffee House, balancing his tray, printed on a 325ml ceramic mug. Dishwasher and microwave safe.</p>', 'The famous turbaned waiter of the Indian Coffee House, on a sturdy ceramic mug.', 65000, NULL, 'mugs', 'Bangalore in the 70s', 1, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('ambassador-car-coaster-set', 'Ambassador Car Coaster Set', 'Set of 4 ceramic coasters', '<p>A set of four cork-backed ceramic coasters, each with a vintage Ambassador car illustration from the 70s. Boxed and ready to gift.</p>', 'Four ceramic coasters featuring the grand old Ambassador in four moods.', 90000, 78000, 'tiles-coasters', 'Vintage Mumbai', 0, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('duck-underbridge-laptop-bag', 'Duck Underbridge Laptop Bag', 'Padded 15" sleeve', '<p>A padded canvas laptop bag (fits up to 15") printed with the beloved ducks-at-the-underbridge illustration. Sturdy zip and a soft interior lining.</p>', 'Ducks at the Frazer Town underbridge on a padded canvas laptop bag.', 180000, NULL, 'bags', 'Bangalore in the 70s', 0, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('old-bangalore-postcard-set', 'Old Bangalore Postcard Set', 'Set of 12', '<p>A set of twelve postcards, each a different old Bangalore scene, printed on lightly textured 300gsm card. Perfect for framing or sending.</p>', 'Twelve postcards of old Bangalore landmarks, printed on textured card.', 45000, NULL, 'stationery', 'Bangalore in the 70s', 1, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
INSERT INTO products (slug, name, subtitle, description, short_desc, price, sale_price, category_slug, collection, featured, primary_image) VALUES ('bougainvillea-bungalow', 'Bougainvillea Bungalow', 'Bangalore in the 70s', '<p>One of the graceful old bungalows of Bangalore, its gate spilling over with bougainvillea and a monkey on the roof. A signed watercolour print.</p>', 'A monkey-topped bungalow spilling over with bougainvillea.', 610000, NULL, 'bangalore-70s', 'Bangalore in the 70s', 0, NULL) ON CONFLICT(slug) DO UPDATE SET price=excluded.price, sale_price=excluded.sale_price, updated_at=datetime('now');
